import { createContext, useState, useContext } from 'react';

const translations = {
  english: {
    // Login
    shop_name: "Austin's Boba Shop",
    user_login: "User Login",
    manager: "Manager",
    cashier: "Cashier",
    customer: "Customer",
    username: "Username",
    username_placeholder: "Enter username",
    password: "Password",
    password_placeholder: "Enter password",
    customer_welcome: "Welcome",
    customer_note: "View the menu or continue as a customer to place an order",
    view_menu: "View Menu",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    continue_as_customer: "Continue as Customer",
    today: "Today",
    sunrise: "Sunrise",
    sunset: "Sunset",
    rain: "Rain",
    
    // Customer View
    loading_menu: "Loading menu…",
    order_here: "Order Here",
    back: "← Back",
    view_cart: "🛒 View Cart",
    add_something_first: "Add something first!",
    welcome: "Welcome!",
    pick_category: "Pick a category, then tap a drink",
    tap_to_customize: "Tap to customize",
    in_cart: "In Cart",
    no_drinks_cat: "No drinks in this category.",
    your_order: "Your Order",
    item: "item",
    items: "items",
    cart_empty_1: "Nothing here yet!",
    cart_empty_2: "Tap a drink to add it.",
    each: "each",
    subtotal: "Subtotal",
    tax: "Tax (8.25%)",
    total: "Total",
    place_order: "Place Order →",
    order_placed: "Order Placed!",
    thank_you: "Thank you for your order!",
    order_number: "Order #",
    start_new: "Start New Order",
    
    // Customizations
    customize: "Customize",
    pick_size: "Pick a size",
    ice_sugar_hint: "ice & sugar: one each · toppings optional",
    size: "Size",
    one_only: " — one only",
    regular: "Regular",
    large: "Large",
    cancel: "Cancel",
    add_to_cart: "Add to cart",
    
    // Payment
    almost_there: "Almost there!",
    how_to_pay: "How would you like to pay?",
    pay_cash: "Cash",
    pay_card: "Card",
    pay_mobile: "Mobile",
    go_back: "Go Back",
    processing: "Processing…",
    confirm_order: "Confirm Order",
    
    // Menu Board
    handcrafted: "Handcrafted drinks",
    ask_barista: "Ask your barista to customize any drink",
    reg: "Reg",
    lg: "Lg",
    custom_badge: "Custom",
    
    // Categories
    sec_milk_teas: "Milk Teas",
    sec_fruit_teas: "Fruit, Green, & Oolong Teas",
    sec_fruit_tab: "Fruit & Tea",
    sec_specialties: "Specialties & Other Drinks",
    sec_specialties_tab: "Specialties",
    sec_toppings: "Toppings / Add-ons",
    sec_toppings_tab: "Toppings",
  },
  spanish: {
    shop_name: "Tienda de Boba de Austin",
    user_login: "Inicio de Sesión",
    manager: "Gerente",
    cashier: "Cajero",
    customer: "Cliente",
    username: "Usuario",
    username_placeholder: "Ingrese usuario",
    password: "Contraseña",
    password_placeholder: "Ingrese contraseña",
    customer_welcome: "Bienvenido",
    customer_note: "Vea el menú o continúe como cliente para ordenar",
    view_menu: "Ver Menú",
    sign_in: "Iniciar Sesión",
    signing_in: "Iniciando...",
    continue_as_customer: "Continuar como Cliente",
    today: "Hoy",
    sunrise: "Amanecer",
    sunset: "Atardecer",
    rain: "Lluvia",
    
    loading_menu: "Cargando menú…",
    order_here: "Ordene Aquí",
    back: "← Volver",
    view_cart: "🛒 Ver Carrito",
    add_something_first: "¡Añade algo primero!",
    welcome: "¡Bienvenido!",
    pick_category: "Elige una categoría y toca una bebida",
    tap_to_customize: "Toca para personalizar",
    in_cart: "En Carrito",
    no_drinks_cat: "No hay bebidas en esta categoría.",
    your_order: "Tu Pedido",
    item: "artículo",
    items: "artículos",
    cart_empty_1: "¡Aún no hay nada aquí!",
    cart_empty_2: "Toca una bebida para añadirla.",
    each: "c/u",
    subtotal: "Subtotal",
    tax: "Impuesto (8.25%)",
    total: "Total",
    place_order: "Realizar Pedido →",
    order_placed: "¡Pedido Realizado!",
    thank_you: "¡Gracias por tu pedido!",
    order_number: "Pedido #",
    start_new: "Comenzar Nuevo Pedido",
    
    customize: "Personalizar",
    pick_size: "Elige un tamaño",
    ice_sugar_hint: "hielo y azúcar: uno de c/u · toppings opcionales",
    size: "Tamaño",
    one_only: " — solo uno",
    regular: "Regular",
    large: "Grande",
    cancel: "Cancelar",
    add_to_cart: "Añadir",
    
    almost_there: "¡Casi listo!",
    how_to_pay: "¿Cómo te gustaría pagar?",
    pay_cash: "Efectivo",
    pay_card: "Tarjeta",
    pay_mobile: "Móvil",
    go_back: "Volver",
    processing: "Procesando…",
    confirm_order: "Confirmar Pedido",
    
    handcrafted: "Bebidas artesanales",
    ask_barista: "Pídele a tu barista que personalice cualquier bebida",
    reg: "Reg",
    lg: "Gde",
    custom_badge: "Personalizable",
    
    sec_milk_teas: "Tés de Leche",
    sec_fruit_teas: "Tés de Fruta, Verde y Oolong",
    sec_fruit_tab: "Fruta y Té",
    sec_specialties: "Especialidades y Otras Bebidas",
    sec_specialties_tab: "Especialidades",
    sec_toppings: "Toppings / Adiciones",
    sec_toppings_tab: "Toppings",
  },
  chinese: {
    shop_name: "Austin的波霸奶茶店",
    user_login: "用户登录",
    manager: "经理",
    cashier: "收银员",
    customer: "顾客",
    username: "用户名",
    username_placeholder: "输入用户名",
    password: "密码",
    password_placeholder: "输入密码",
    customer_welcome: "欢迎",
    customer_note: "查看菜单或作为顾客继续下单",
    view_menu: "查看菜单",
    sign_in: "登录",
    signing_in: "登录中...",
    continue_as_customer: "作为顾客继续",
    today: "今天",
    sunrise: "日出",
    sunset: "日落",
    rain: "雨",
    
    loading_menu: "加载菜单中…",
    order_here: "在此点单",
    back: "← 返回",
    view_cart: "🛒 查看购物车",
    add_something_first: "请先添加商品！",
    welcome: "欢迎！",
    pick_category: "选择分类，然后点击饮品",
    tap_to_customize: "点击以自定义",
    in_cart: "在购物车:",
    no_drinks_cat: "该分类下没有饮品。",
    your_order: "您的订单",
    item: "件商品",
    items: "件商品",
    cart_empty_1: "购物车是空的！",
    cart_empty_2: "点击饮品添加。",
    each: "每件",
    subtotal: "小计",
    tax: "税 (8.25%)",
    total: "总计",
    place_order: "提交订单 →",
    order_placed: "订单已提交！",
    thank_you: "感谢您的订购！",
    order_number: "订单号 #",
    start_new: "开始新订单",
    
    customize: "自定义",
    pick_size: "选择杯型",
    ice_sugar_hint: "冰块和糖度：各选一项 · 加料可选",
    size: "杯型",
    one_only: " — 仅限一项",
    regular: "中杯",
    large: "大杯",
    cancel: "取消",
    add_to_cart: "加入购物车",
    
    almost_there: "马上就好！",
    how_to_pay: "您想如何付款？",
    pay_cash: "现金",
    pay_card: "刷卡",
    pay_mobile: "手机支付",
    go_back: "返回",
    processing: "处理中…",
    confirm_order: "确认订单",
    
    handcrafted: "手工调制饮品",
    ask_barista: "请告诉咖啡师您想如何客制化饮品",
    reg: "中",
    lg: "大",
    custom_badge: "可客制化",
    
    sec_milk_teas: "奶茶",
    sec_fruit_teas: "果茶、绿茶和乌龙茶",
    sec_fruit_tab: "果茶 & 茶",
    sec_specialties: "特色饮品及其他",
    sec_specialties_tab: "特色饮品",
    sec_toppings: "加料",
    sec_toppings_tab: "加料",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('english');

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);